repos:

# - repo: https://gitlab.com/vojko.pribudic/pre-commit-update
#   rev: v0.1.1
#   hooks:
#     - id: pre-commit-update

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout
