PROJECT_DATA_DIR: str = "./.data"
CF_WAF_FILTER_VALUES_DIR: str = "cf_waf_filter_rules"

CF_WAF_IP_BLOCKS_FILE: str = "block_ips.txt"
CF_WAF_COUNTRY_BLOCKS_FILE: str = "countries.txt"
CF_WAF_UA_BLOCKS_FILE: str = "ua_strings.txt"

IP_BLOCKS_FILE: str = f"{PROJECT_DATA_DIR}/{CF_WAF_FILTER_VALUES_DIR}/{CF_WAF_IP_BLOCKS_FILE}"
COUNTRY_BLOCKS_FILE: str = f"{PROJECT_DATA_DIR}/{CF_WAF_FILTER_VALUES_DIR}/{CF_WAF_COUNTRY_BLOCKS_FILE}"
UA_BLOCKS_FILE: str = f"{PROJECT_DATA_DIR}/{CF_WAF_FILTER_VALUES_DIR}/{CF_WAF_UA_BLOCKS_FILE}"
