[project]
name = "cfapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "database-lib",
    "depends-lib",
    "hishel>=0.1.1",
    "http-lib",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "pydantic>=2.10.6",
    "settings-lib",
]

[project.scripts]
hello = "cfapi:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
database-lib = { workspace = true }
depends-lib = { workspace = true }
http-lib = { workspace = true }
settings-lib = { workspace = true }
