[project]
name = "domain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.37",
]

[project.scripts]
hello = "domain:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
